# Generated by Django 5.1.3 on 2024-12-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('information', models.TextField(verbose_name='Інформація')),
                ('date', models.DateTimeField(verbose_name='Час публікації')),
            ],
            options={
                'verbose_name': 'Майстер-клас',
                'verbose_name_plural': 'Майстер-класи',
            },
        ),
    ]
