# Generated by Django 5.1.3 on 2024-12-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterClasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='instructionImg1',
            field=models.ImageField(blank=True, null=True, upload_to='masterclass_images/', verbose_name='Фото-інструкція1'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='instructionImg2',
            field=models.ImageField(blank=True, null=True, upload_to='masterclass_images/', verbose_name='Фото-інструкція2'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='instructionImg3',
            field=models.ImageField(blank=True, null=True, upload_to='masterclass_images/', verbose_name='Фото-інструкція3'),
        ),
    ]
