# Generated by Django 4.1.7 on 2024-12-17 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterClasses', '0003_remove_masterclass_instructionimg3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='examplesImg1',
            field=models.ImageField(blank=True, null=True, upload_to='masterClasses/static/img', verbose_name='Фото-приклад1'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='examplesImg2',
            field=models.ImageField(blank=True, null=True, upload_to='masterClasses/static/img', verbose_name='Фото-приклад2'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='examplesImg3',
            field=models.ImageField(blank=True, null=True, upload_to='masterClasses/static/img', verbose_name='Фото-приклад3'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='injuredImg1',
            field=models.ImageField(blank=True, null=True, upload_to='masterClasses/static/img', verbose_name='Фото на пораненому 1'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='injuredImg2',
            field=models.ImageField(blank=True, null=True, upload_to='masterClasses/static/img', verbose_name='Фото на пораненому 2'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='injuredImg3',
            field=models.ImageField(blank=True, null=True, upload_to='masterClasses/static/img', verbose_name='Фото на пораненому 3'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='instructionImg1',
            field=models.ImageField(blank=True, null=True, upload_to='masterClasses/static/img', verbose_name='Фото-інструкція1'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='instructionImg2',
            field=models.ImageField(blank=True, null=True, upload_to='masterClasses/static/img', verbose_name='Фото-інструкція2'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Коментарій')),
                ('date', models.DateTimeField(verbose_name='Час публікації')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
