# Generated by Django 4.1.7 on 2024-12-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterClasses', '0004_alter_masterclass_examplesimg1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='examplesImg1',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Фото-приклад1'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='examplesImg2',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Фото-приклад2'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='examplesImg3',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Фото-приклад3'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='injuredImg1',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Фото на пораненому 1'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='injuredImg2',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Фото на пораненому 2'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='injuredImg3',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Фото на пораненому 3'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='instructionImg1',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Фото-інструкція1'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='instructionImg2',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Фото-інструкція2'),
        ),
    ]
