# Generated by Django 4.1.7 on 2024-12-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterClasses', '0004_alter_masterclass_date_comments'),
        ('masterClasses', '0006_alter_masterclass_examplesimg1_and_more'),
    ]

    operations = [
    ]
