# Generated by Django 4.1.7 on 2024-12-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterClasses', '0007_merge_20241217_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
    ]
